// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	jwt "github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"
)

// Claims is an autogenerated mock type for the Claims type
type Claims struct {
	mock.Mock
}

// GetAudience provides a mock function with given fields:
func (_m *Claims) GetAudience() (jwt.ClaimStrings, error) {
	ret := _m.Called()

	var r0 jwt.ClaimStrings
	var r1 error
	if rf, ok := ret.Get(0).(func() (jwt.ClaimStrings, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() jwt.ClaimStrings); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwt.ClaimStrings)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExpirationTime provides a mock function with given fields:
func (_m *Claims) GetExpirationTime() (*jwt.NumericDate, error) {
	ret := _m.Called()

	var r0 *jwt.NumericDate
	var r1 error
	if rf, ok := ret.Get(0).(func() (*jwt.NumericDate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *jwt.NumericDate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.NumericDate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIssuedAt provides a mock function with given fields:
func (_m *Claims) GetIssuedAt() (*jwt.NumericDate, error) {
	ret := _m.Called()

	var r0 *jwt.NumericDate
	var r1 error
	if rf, ok := ret.Get(0).(func() (*jwt.NumericDate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *jwt.NumericDate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.NumericDate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIssuer provides a mock function with given fields:
func (_m *Claims) GetIssuer() (string, error) {
	ret := _m.Called()

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNotBefore provides a mock function with given fields:
func (_m *Claims) GetNotBefore() (*jwt.NumericDate, error) {
	ret := _m.Called()

	var r0 *jwt.NumericDate
	var r1 error
	if rf, ok := ret.Get(0).(func() (*jwt.NumericDate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *jwt.NumericDate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.NumericDate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubject provides a mock function with given fields:
func (_m *Claims) GetSubject() (string, error) {
	ret := _m.Called()

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClaims creates a new instance of Claims. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClaims(t interface {
	mock.TestingT
	Cleanup(func())
}) *Claims {
	mock := &Claims{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
