// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	issuer "github.com/jannfis/argocd-agent/internal/issuer"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockIssuer is an autogenerated mock type for the Issuer type
type MockIssuer struct {
	mock.Mock
}

type MockIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIssuer) EXPECT() *MockIssuer_Expecter {
	return &MockIssuer_Expecter{mock: &_m.Mock}
}

// IssueAccessToken provides a mock function with given fields: client, exp
func (_m *MockIssuer) IssueAccessToken(client string, exp time.Duration) (string, error) {
	ret := _m.Called(client, exp)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Duration) (string, error)); ok {
		return rf(client, exp)
	}
	if rf, ok := ret.Get(0).(func(string, time.Duration) string); ok {
		r0 = rf(client, exp)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, time.Duration) error); ok {
		r1 = rf(client, exp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIssuer_IssueAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueAccessToken'
type MockIssuer_IssueAccessToken_Call struct {
	*mock.Call
}

// IssueAccessToken is a helper method to define mock.On call
//   - client string
//   - exp time.Duration
func (_e *MockIssuer_Expecter) IssueAccessToken(client interface{}, exp interface{}) *MockIssuer_IssueAccessToken_Call {
	return &MockIssuer_IssueAccessToken_Call{Call: _e.mock.On("IssueAccessToken", client, exp)}
}

func (_c *MockIssuer_IssueAccessToken_Call) Run(run func(client string, exp time.Duration)) *MockIssuer_IssueAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockIssuer_IssueAccessToken_Call) Return(_a0 string, _a1 error) *MockIssuer_IssueAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIssuer_IssueAccessToken_Call) RunAndReturn(run func(string, time.Duration) (string, error)) *MockIssuer_IssueAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// IssueRefreshToken provides a mock function with given fields: client, exp
func (_m *MockIssuer) IssueRefreshToken(client string, exp time.Duration) (string, error) {
	ret := _m.Called(client, exp)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Duration) (string, error)); ok {
		return rf(client, exp)
	}
	if rf, ok := ret.Get(0).(func(string, time.Duration) string); ok {
		r0 = rf(client, exp)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, time.Duration) error); ok {
		r1 = rf(client, exp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIssuer_IssueRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueRefreshToken'
type MockIssuer_IssueRefreshToken_Call struct {
	*mock.Call
}

// IssueRefreshToken is a helper method to define mock.On call
//   - client string
//   - exp time.Duration
func (_e *MockIssuer_Expecter) IssueRefreshToken(client interface{}, exp interface{}) *MockIssuer_IssueRefreshToken_Call {
	return &MockIssuer_IssueRefreshToken_Call{Call: _e.mock.On("IssueRefreshToken", client, exp)}
}

func (_c *MockIssuer_IssueRefreshToken_Call) Run(run func(client string, exp time.Duration)) *MockIssuer_IssueRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockIssuer_IssueRefreshToken_Call) Return(_a0 string, _a1 error) *MockIssuer_IssueRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIssuer_IssueRefreshToken_Call) RunAndReturn(run func(string, time.Duration) (string, error)) *MockIssuer_IssueRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function with given fields: token
func (_m *MockIssuer) ValidateAccessToken(token string) (issuer.Claims, error) {
	ret := _m.Called(token)

	var r0 issuer.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (issuer.Claims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) issuer.Claims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(issuer.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIssuer_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockIssuer_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - token string
func (_e *MockIssuer_Expecter) ValidateAccessToken(token interface{}) *MockIssuer_ValidateAccessToken_Call {
	return &MockIssuer_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", token)}
}

func (_c *MockIssuer_ValidateAccessToken_Call) Run(run func(token string)) *MockIssuer_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIssuer_ValidateAccessToken_Call) Return(_a0 issuer.Claims, _a1 error) *MockIssuer_ValidateAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIssuer_ValidateAccessToken_Call) RunAndReturn(run func(string) (issuer.Claims, error)) *MockIssuer_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRefreshToken provides a mock function with given fields: token
func (_m *MockIssuer) ValidateRefreshToken(token string) (issuer.Claims, error) {
	ret := _m.Called(token)

	var r0 issuer.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (issuer.Claims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) issuer.Claims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(issuer.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIssuer_ValidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRefreshToken'
type MockIssuer_ValidateRefreshToken_Call struct {
	*mock.Call
}

// ValidateRefreshToken is a helper method to define mock.On call
//   - token string
func (_e *MockIssuer_Expecter) ValidateRefreshToken(token interface{}) *MockIssuer_ValidateRefreshToken_Call {
	return &MockIssuer_ValidateRefreshToken_Call{Call: _e.mock.On("ValidateRefreshToken", token)}
}

func (_c *MockIssuer_ValidateRefreshToken_Call) Run(run func(token string)) *MockIssuer_ValidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockIssuer_ValidateRefreshToken_Call) Return(_a0 issuer.Claims, _a1 error) *MockIssuer_ValidateRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIssuer_ValidateRefreshToken_Call) RunAndReturn(run func(string) (issuer.Claims, error)) *MockIssuer_ValidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIssuer creates a new instance of MockIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIssuer {
	mock := &MockIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
