// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	issuer "github.com/jannfis/argocd-agent/internal/issuer"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Issuer is an autogenerated mock type for the Issuer type
type Issuer struct {
	mock.Mock
}

// IssueAccessToken provides a mock function with given fields: client, exp
func (_m *Issuer) IssueAccessToken(client string, exp time.Duration) (string, error) {
	ret := _m.Called(client, exp)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Duration) (string, error)); ok {
		return rf(client, exp)
	}
	if rf, ok := ret.Get(0).(func(string, time.Duration) string); ok {
		r0 = rf(client, exp)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, time.Duration) error); ok {
		r1 = rf(client, exp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IssueRefreshToken provides a mock function with given fields: client, exp
func (_m *Issuer) IssueRefreshToken(client string, exp time.Duration) (string, error) {
	ret := _m.Called(client, exp)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Duration) (string, error)); ok {
		return rf(client, exp)
	}
	if rf, ok := ret.Get(0).(func(string, time.Duration) string); ok {
		r0 = rf(client, exp)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, time.Duration) error); ok {
		r1 = rf(client, exp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateAccessToken provides a mock function with given fields: token
func (_m *Issuer) ValidateAccessToken(token string) (issuer.Claims, error) {
	ret := _m.Called(token)

	var r0 issuer.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (issuer.Claims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) issuer.Claims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(issuer.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateRefreshToken provides a mock function with given fields: token
func (_m *Issuer) ValidateRefreshToken(token string) (issuer.Claims, error) {
	ret := _m.Called(token)

	var r0 issuer.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (issuer.Claims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) issuer.Claims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(issuer.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIssuer creates a new instance of Issuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Issuer {
	mock := &Issuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
