// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	issuer "github.com/jannfis/argocd-agent/internal/issuer"
	mock "github.com/stretchr/testify/mock"
)

// MockJwtIssuerOption is an autogenerated mock type for the JwtIssuerOption type
type MockJwtIssuerOption struct {
	mock.Mock
}

type MockJwtIssuerOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwtIssuerOption) EXPECT() *MockJwtIssuerOption_Expecter {
	return &MockJwtIssuerOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: i
func (_m *MockJwtIssuerOption) Execute(i *issuer.JwtIssuer) error {
	ret := _m.Called(i)

	var r0 error
	if rf, ok := ret.Get(0).(func(*issuer.JwtIssuer) error); ok {
		r0 = rf(i)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockJwtIssuerOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockJwtIssuerOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - i *issuer.JwtIssuer
func (_e *MockJwtIssuerOption_Expecter) Execute(i interface{}) *MockJwtIssuerOption_Execute_Call {
	return &MockJwtIssuerOption_Execute_Call{Call: _e.mock.On("Execute", i)}
}

func (_c *MockJwtIssuerOption_Execute_Call) Run(run func(i *issuer.JwtIssuer)) *MockJwtIssuerOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*issuer.JwtIssuer))
	})
	return _c
}

func (_c *MockJwtIssuerOption_Execute_Call) Return(_a0 error) *MockJwtIssuerOption_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJwtIssuerOption_Execute_Call) RunAndReturn(run func(*issuer.JwtIssuer) error) *MockJwtIssuerOption_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwtIssuerOption creates a new instance of MockJwtIssuerOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwtIssuerOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwtIssuerOption {
	mock := &MockJwtIssuerOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
