// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	issuer "github.com/jannfis/argocd-agent/internal/issuer"
	mock "github.com/stretchr/testify/mock"
)

// JwtIssuerOption is an autogenerated mock type for the JwtIssuerOption type
type JwtIssuerOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: i
func (_m *JwtIssuerOption) Execute(i *issuer.JwtIssuer) error {
	ret := _m.Called(i)

	var r0 error
	if rf, ok := ret.Get(0).(func(*issuer.JwtIssuer) error); ok {
		r0 = rf(i)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewJwtIssuerOption creates a new instance of JwtIssuerOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJwtIssuerOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *JwtIssuerOption {
	mock := &JwtIssuerOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
