// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: appstream.proto

package appstreamapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AppStreamClient is the client API for AppStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppStreamClient interface {
	Subscribe(ctx context.Context, opts ...grpc.CallOption) (AppStream_SubscribeClient, error)
	Push(ctx context.Context, opts ...grpc.CallOption) (AppStream_PushClient, error)
}

type appStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewAppStreamClient(cc grpc.ClientConnInterface) AppStreamClient {
	return &appStreamClient{cc}
}

func (c *appStreamClient) Subscribe(ctx context.Context, opts ...grpc.CallOption) (AppStream_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &AppStream_ServiceDesc.Streams[0], "/appstreamapi.AppStream/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &appStreamSubscribeClient{stream}
	return x, nil
}

type AppStream_SubscribeClient interface {
	Send(*Subscription) error
	Recv() (*Subscription, error)
	grpc.ClientStream
}

type appStreamSubscribeClient struct {
	grpc.ClientStream
}

func (x *appStreamSubscribeClient) Send(m *Subscription) error {
	return x.ClientStream.SendMsg(m)
}

func (x *appStreamSubscribeClient) Recv() (*Subscription, error) {
	m := new(Subscription)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *appStreamClient) Push(ctx context.Context, opts ...grpc.CallOption) (AppStream_PushClient, error) {
	stream, err := c.cc.NewStream(ctx, &AppStream_ServiceDesc.Streams[1], "/appstreamapi.AppStream/Push", opts...)
	if err != nil {
		return nil, err
	}
	x := &appStreamPushClient{stream}
	return x, nil
}

type AppStream_PushClient interface {
	Send(*Subscription) error
	CloseAndRecv() (*PushSummary, error)
	grpc.ClientStream
}

type appStreamPushClient struct {
	grpc.ClientStream
}

func (x *appStreamPushClient) Send(m *Subscription) error {
	return x.ClientStream.SendMsg(m)
}

func (x *appStreamPushClient) CloseAndRecv() (*PushSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PushSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AppStreamServer is the server API for AppStream service.
// All implementations must embed UnimplementedAppStreamServer
// for forward compatibility
type AppStreamServer interface {
	Subscribe(AppStream_SubscribeServer) error
	Push(AppStream_PushServer) error
	mustEmbedUnimplementedAppStreamServer()
}

// UnimplementedAppStreamServer must be embedded to have forward compatible implementations.
type UnimplementedAppStreamServer struct {
}

func (UnimplementedAppStreamServer) Subscribe(AppStream_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedAppStreamServer) Push(AppStream_PushServer) error {
	return status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedAppStreamServer) mustEmbedUnimplementedAppStreamServer() {}

// UnsafeAppStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppStreamServer will
// result in compilation errors.
type UnsafeAppStreamServer interface {
	mustEmbedUnimplementedAppStreamServer()
}

func RegisterAppStreamServer(s grpc.ServiceRegistrar, srv AppStreamServer) {
	s.RegisterService(&AppStream_ServiceDesc, srv)
}

func _AppStream_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AppStreamServer).Subscribe(&appStreamSubscribeServer{stream})
}

type AppStream_SubscribeServer interface {
	Send(*Subscription) error
	Recv() (*Subscription, error)
	grpc.ServerStream
}

type appStreamSubscribeServer struct {
	grpc.ServerStream
}

func (x *appStreamSubscribeServer) Send(m *Subscription) error {
	return x.ServerStream.SendMsg(m)
}

func (x *appStreamSubscribeServer) Recv() (*Subscription, error) {
	m := new(Subscription)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AppStream_Push_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AppStreamServer).Push(&appStreamPushServer{stream})
}

type AppStream_PushServer interface {
	SendAndClose(*PushSummary) error
	Recv() (*Subscription, error)
	grpc.ServerStream
}

type appStreamPushServer struct {
	grpc.ServerStream
}

func (x *appStreamPushServer) SendAndClose(m *PushSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *appStreamPushServer) Recv() (*Subscription, error) {
	m := new(Subscription)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AppStream_ServiceDesc is the grpc.ServiceDesc for AppStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "appstreamapi.AppStream",
	HandlerType: (*AppStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _AppStream_Subscribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Push",
			Handler:       _AppStream_Push_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "appstream.proto",
}
