// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: appstream.proto

package appstreamapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AppStreamClient is the client API for AppStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppStreamClient interface {
	Subscribe(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*SubscriptionStream, error)
}

type appStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewAppStreamClient(cc grpc.ClientConnInterface) AppStreamClient {
	return &appStreamClient{cc}
}

func (c *appStreamClient) Subscribe(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*SubscriptionStream, error) {
	out := new(SubscriptionStream)
	err := c.cc.Invoke(ctx, "/appstreamapi.AppStream/Subscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppStreamServer is the server API for AppStream service.
// All implementations must embed UnimplementedAppStreamServer
// for forward compatibility
type AppStreamServer interface {
	Subscribe(context.Context, *Subscription) (*SubscriptionStream, error)
	mustEmbedUnimplementedAppStreamServer()
}

// UnimplementedAppStreamServer must be embedded to have forward compatible implementations.
type UnimplementedAppStreamServer struct {
}

func (UnimplementedAppStreamServer) Subscribe(context.Context, *Subscription) (*SubscriptionStream, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedAppStreamServer) mustEmbedUnimplementedAppStreamServer() {}

// UnsafeAppStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppStreamServer will
// result in compilation errors.
type UnsafeAppStreamServer interface {
	mustEmbedUnimplementedAppStreamServer()
}

func RegisterAppStreamServer(s grpc.ServiceRegistrar, srv AppStreamServer) {
	s.RegisterService(&AppStream_ServiceDesc, srv)
}

func _AppStream_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Subscription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppStreamServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/appstreamapi.AppStream/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppStreamServer).Subscribe(ctx, req.(*Subscription))
	}
	return interceptor(ctx, in, info, handler)
}

// AppStream_ServiceDesc is the grpc.ServiceDesc for AppStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "appstreamapi.AppStream",
	HandlerType: (*AppStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _AppStream_Subscribe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "appstream.proto",
}
