// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	auth "github.com/jannfis/argocd-agent/internal/auth"
	mock "github.com/stretchr/testify/mock"
)

// Method is an autogenerated mock type for the Method type
type Method struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: credentials
func (_m *Method) Authenticate(credentials auth.Credentials) (string, error) {
	ret := _m.Called(credentials)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(auth.Credentials) (string, error)); ok {
		return rf(credentials)
	}
	if rf, ok := ret.Get(0).(func(auth.Credentials) string); ok {
		r0 = rf(credentials)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(auth.Credentials) error); ok {
		r1 = rf(credentials)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMethod creates a new instance of Method. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMethod(t interface {
	mock.TestingT
	Cleanup(func())
}) *Method {
	mock := &Method{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
