// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	context "context"

	backend "github.com/jannfis/argocd-agent/internal/backend"

	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1"
)

// MockApplication is an autogenerated mock type for the Application type
type MockApplication struct {
	mock.Mock
}

type MockApplication_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApplication) EXPECT() *MockApplication_Expecter {
	return &MockApplication_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, app
func (_m *MockApplication) Create(ctx context.Context, app *v1alpha1.Application) (*v1alpha1.Application, error) {
	ret := _m.Called(ctx, app)

	var r0 *v1alpha1.Application
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.Application) (*v1alpha1.Application, error)); ok {
		return rf(ctx, app)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.Application) *v1alpha1.Application); ok {
		r0 = rf(ctx, app)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Application)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.Application) error); ok {
		r1 = rf(ctx, app)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApplication_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockApplication_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - app *v1alpha1.Application
func (_e *MockApplication_Expecter) Create(ctx interface{}, app interface{}) *MockApplication_Create_Call {
	return &MockApplication_Create_Call{Call: _e.mock.On("Create", ctx, app)}
}

func (_c *MockApplication_Create_Call) Run(run func(ctx context.Context, app *v1alpha1.Application)) *MockApplication_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1alpha1.Application))
	})
	return _c
}

func (_c *MockApplication_Create_Call) Return(_a0 *v1alpha1.Application, _a1 error) *MockApplication_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApplication_Create_Call) RunAndReturn(run func(context.Context, *v1alpha1.Application) (*v1alpha1.Application, error)) *MockApplication_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, namespace
func (_m *MockApplication) Delete(ctx context.Context, name string, namespace string) error {
	ret := _m.Called(ctx, name, namespace)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, name, namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApplication_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockApplication_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - namespace string
func (_e *MockApplication_Expecter) Delete(ctx interface{}, name interface{}, namespace interface{}) *MockApplication_Delete_Call {
	return &MockApplication_Delete_Call{Call: _e.mock.On("Delete", ctx, name, namespace)}
}

func (_c *MockApplication_Delete_Call) Run(run func(ctx context.Context, name string, namespace string)) *MockApplication_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockApplication_Delete_Call) Return(_a0 error) *MockApplication_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApplication_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockApplication_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, namespace
func (_m *MockApplication) Get(ctx context.Context, name string, namespace string) (*v1alpha1.Application, error) {
	ret := _m.Called(ctx, name, namespace)

	var r0 *v1alpha1.Application
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.Application, error)); ok {
		return rf(ctx, name, namespace)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.Application); ok {
		r0 = rf(ctx, name, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Application)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApplication_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockApplication_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - namespace string
func (_e *MockApplication_Expecter) Get(ctx interface{}, name interface{}, namespace interface{}) *MockApplication_Get_Call {
	return &MockApplication_Get_Call{Call: _e.mock.On("Get", ctx, name, namespace)}
}

func (_c *MockApplication_Get_Call) Run(run func(ctx context.Context, name string, namespace string)) *MockApplication_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockApplication_Get_Call) Return(_a0 *v1alpha1.Application, _a1 error) *MockApplication_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApplication_Get_Call) RunAndReturn(run func(context.Context, string, string) (*v1alpha1.Application, error)) *MockApplication_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, selector
func (_m *MockApplication) List(ctx context.Context, selector backend.ApplicationSelector) ([]v1alpha1.Application, error) {
	ret := _m.Called(ctx, selector)

	var r0 []v1alpha1.Application
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, backend.ApplicationSelector) ([]v1alpha1.Application, error)); ok {
		return rf(ctx, selector)
	}
	if rf, ok := ret.Get(0).(func(context.Context, backend.ApplicationSelector) []v1alpha1.Application); ok {
		r0 = rf(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1alpha1.Application)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, backend.ApplicationSelector) error); ok {
		r1 = rf(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApplication_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockApplication_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - selector backend.ApplicationSelector
func (_e *MockApplication_Expecter) List(ctx interface{}, selector interface{}) *MockApplication_List_Call {
	return &MockApplication_List_Call{Call: _e.mock.On("List", ctx, selector)}
}

func (_c *MockApplication_List_Call) Run(run func(ctx context.Context, selector backend.ApplicationSelector)) *MockApplication_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(backend.ApplicationSelector))
	})
	return _c
}

func (_c *MockApplication_List_Call) Return(_a0 []v1alpha1.Application, _a1 error) *MockApplication_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApplication_List_Call) RunAndReturn(run func(context.Context, backend.ApplicationSelector) ([]v1alpha1.Application, error)) *MockApplication_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, name, namespace, patch
func (_m *MockApplication) Patch(ctx context.Context, name string, namespace string, patch []byte) (*v1alpha1.Application, error) {
	ret := _m.Called(ctx, name, namespace, patch)

	var r0 *v1alpha1.Application
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) (*v1alpha1.Application, error)); ok {
		return rf(ctx, name, namespace, patch)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, []byte) *v1alpha1.Application); ok {
		r0 = rf(ctx, name, namespace, patch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Application)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, []byte) error); ok {
		r1 = rf(ctx, name, namespace, patch)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApplication_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockApplication_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - namespace string
//   - patch []byte
func (_e *MockApplication_Expecter) Patch(ctx interface{}, name interface{}, namespace interface{}, patch interface{}) *MockApplication_Patch_Call {
	return &MockApplication_Patch_Call{Call: _e.mock.On("Patch", ctx, name, namespace, patch)}
}

func (_c *MockApplication_Patch_Call) Run(run func(ctx context.Context, name string, namespace string, patch []byte)) *MockApplication_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].([]byte))
	})
	return _c
}

func (_c *MockApplication_Patch_Call) Return(_a0 *v1alpha1.Application, _a1 error) *MockApplication_Patch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApplication_Patch_Call) RunAndReturn(run func(context.Context, string, string, []byte) (*v1alpha1.Application, error)) *MockApplication_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// StartInformer provides a mock function with given fields: ctx
func (_m *MockApplication) StartInformer(ctx context.Context) {
	_m.Called(ctx)
}

// MockApplication_StartInformer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartInformer'
type MockApplication_StartInformer_Call struct {
	*mock.Call
}

// StartInformer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockApplication_Expecter) StartInformer(ctx interface{}) *MockApplication_StartInformer_Call {
	return &MockApplication_StartInformer_Call{Call: _e.mock.On("StartInformer", ctx)}
}

func (_c *MockApplication_StartInformer_Call) Run(run func(ctx context.Context)) *MockApplication_StartInformer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockApplication_StartInformer_Call) Return() *MockApplication_StartInformer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockApplication_StartInformer_Call) RunAndReturn(run func(context.Context)) *MockApplication_StartInformer_Call {
	_c.Call.Return(run)
	return _c
}

// SupportsPatch provides a mock function with given fields:
func (_m *MockApplication) SupportsPatch() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockApplication_SupportsPatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportsPatch'
type MockApplication_SupportsPatch_Call struct {
	*mock.Call
}

// SupportsPatch is a helper method to define mock.On call
func (_e *MockApplication_Expecter) SupportsPatch() *MockApplication_SupportsPatch_Call {
	return &MockApplication_SupportsPatch_Call{Call: _e.mock.On("SupportsPatch")}
}

func (_c *MockApplication_SupportsPatch_Call) Run(run func()) *MockApplication_SupportsPatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockApplication_SupportsPatch_Call) Return(_a0 bool) *MockApplication_SupportsPatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApplication_SupportsPatch_Call) RunAndReturn(run func() bool) *MockApplication_SupportsPatch_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, app
func (_m *MockApplication) Update(ctx context.Context, app *v1alpha1.Application) (*v1alpha1.Application, error) {
	ret := _m.Called(ctx, app)

	var r0 *v1alpha1.Application
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.Application) (*v1alpha1.Application, error)); ok {
		return rf(ctx, app)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.Application) *v1alpha1.Application); ok {
		r0 = rf(ctx, app)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Application)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.Application) error); ok {
		r1 = rf(ctx, app)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApplication_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockApplication_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - app *v1alpha1.Application
func (_e *MockApplication_Expecter) Update(ctx interface{}, app interface{}) *MockApplication_Update_Call {
	return &MockApplication_Update_Call{Call: _e.mock.On("Update", ctx, app)}
}

func (_c *MockApplication_Update_Call) Run(run func(ctx context.Context, app *v1alpha1.Application)) *MockApplication_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1alpha1.Application))
	})
	return _c
}

func (_c *MockApplication_Update_Call) Return(_a0 *v1alpha1.Application, _a1 error) *MockApplication_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApplication_Update_Call) RunAndReturn(run func(context.Context, *v1alpha1.Application) (*v1alpha1.Application, error)) *MockApplication_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockApplication creates a new instance of MockApplication. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApplication(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApplication {
	mock := &MockApplication{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
