// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	workqueue "k8s.io/client-go/util/workqueue"
)

// MockQueuePair is an autogenerated mock type for the QueuePair type
type MockQueuePair struct {
	mock.Mock
}

type MockQueuePair_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueuePair) EXPECT() *MockQueuePair_Expecter {
	return &MockQueuePair_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: name
func (_m *MockQueuePair) Create(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueuePair_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockQueuePair_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - name string
func (_e *MockQueuePair_Expecter) Create(name interface{}) *MockQueuePair_Create_Call {
	return &MockQueuePair_Create_Call{Call: _e.mock.On("Create", name)}
}

func (_c *MockQueuePair_Create_Call) Run(run func(name string)) *MockQueuePair_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockQueuePair_Create_Call) Return(_a0 error) *MockQueuePair_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueuePair_Create_Call) RunAndReturn(run func(string) error) *MockQueuePair_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: name, shutdown
func (_m *MockQueuePair) Delete(name string, shutdown bool) error {
	ret := _m.Called(name, shutdown)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, bool) error); ok {
		r0 = rf(name, shutdown)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueuePair_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockQueuePair_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - name string
//   - shutdown bool
func (_e *MockQueuePair_Expecter) Delete(name interface{}, shutdown interface{}) *MockQueuePair_Delete_Call {
	return &MockQueuePair_Delete_Call{Call: _e.mock.On("Delete", name, shutdown)}
}

func (_c *MockQueuePair_Delete_Call) Run(run func(name string, shutdown bool)) *MockQueuePair_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *MockQueuePair_Delete_Call) Return(_a0 error) *MockQueuePair_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueuePair_Delete_Call) RunAndReturn(run func(string, bool) error) *MockQueuePair_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// HasQueuePair provides a mock function with given fields: name
func (_m *MockQueuePair) HasQueuePair(name string) bool {
	ret := _m.Called(name)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockQueuePair_HasQueuePair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasQueuePair'
type MockQueuePair_HasQueuePair_Call struct {
	*mock.Call
}

// HasQueuePair is a helper method to define mock.On call
//   - name string
func (_e *MockQueuePair_Expecter) HasQueuePair(name interface{}) *MockQueuePair_HasQueuePair_Call {
	return &MockQueuePair_HasQueuePair_Call{Call: _e.mock.On("HasQueuePair", name)}
}

func (_c *MockQueuePair_HasQueuePair_Call) Run(run func(name string)) *MockQueuePair_HasQueuePair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockQueuePair_HasQueuePair_Call) Return(_a0 bool) *MockQueuePair_HasQueuePair_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueuePair_HasQueuePair_Call) RunAndReturn(run func(string) bool) *MockQueuePair_HasQueuePair_Call {
	_c.Call.Return(run)
	return _c
}

// Len provides a mock function with given fields:
func (_m *MockQueuePair) Len() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockQueuePair_Len_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Len'
type MockQueuePair_Len_Call struct {
	*mock.Call
}

// Len is a helper method to define mock.On call
func (_e *MockQueuePair_Expecter) Len() *MockQueuePair_Len_Call {
	return &MockQueuePair_Len_Call{Call: _e.mock.On("Len")}
}

func (_c *MockQueuePair_Len_Call) Run(run func()) *MockQueuePair_Len_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueuePair_Len_Call) Return(_a0 int) *MockQueuePair_Len_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueuePair_Len_Call) RunAndReturn(run func() int) *MockQueuePair_Len_Call {
	_c.Call.Return(run)
	return _c
}

// Names provides a mock function with given fields:
func (_m *MockQueuePair) Names() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockQueuePair_Names_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Names'
type MockQueuePair_Names_Call struct {
	*mock.Call
}

// Names is a helper method to define mock.On call
func (_e *MockQueuePair_Expecter) Names() *MockQueuePair_Names_Call {
	return &MockQueuePair_Names_Call{Call: _e.mock.On("Names")}
}

func (_c *MockQueuePair_Names_Call) Run(run func()) *MockQueuePair_Names_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueuePair_Names_Call) Return(_a0 []string) *MockQueuePair_Names_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueuePair_Names_Call) RunAndReturn(run func() []string) *MockQueuePair_Names_Call {
	_c.Call.Return(run)
	return _c
}

// RecvQ provides a mock function with given fields: name
func (_m *MockQueuePair) RecvQ(name string) workqueue.RateLimitingInterface {
	ret := _m.Called(name)

	var r0 workqueue.RateLimitingInterface
	if rf, ok := ret.Get(0).(func(string) workqueue.RateLimitingInterface); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(workqueue.RateLimitingInterface)
		}
	}

	return r0
}

// MockQueuePair_RecvQ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvQ'
type MockQueuePair_RecvQ_Call struct {
	*mock.Call
}

// RecvQ is a helper method to define mock.On call
//   - name string
func (_e *MockQueuePair_Expecter) RecvQ(name interface{}) *MockQueuePair_RecvQ_Call {
	return &MockQueuePair_RecvQ_Call{Call: _e.mock.On("RecvQ", name)}
}

func (_c *MockQueuePair_RecvQ_Call) Run(run func(name string)) *MockQueuePair_RecvQ_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockQueuePair_RecvQ_Call) Return(_a0 workqueue.RateLimitingInterface) *MockQueuePair_RecvQ_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueuePair_RecvQ_Call) RunAndReturn(run func(string) workqueue.RateLimitingInterface) *MockQueuePair_RecvQ_Call {
	_c.Call.Return(run)
	return _c
}

// SendQ provides a mock function with given fields: name
func (_m *MockQueuePair) SendQ(name string) workqueue.RateLimitingInterface {
	ret := _m.Called(name)

	var r0 workqueue.RateLimitingInterface
	if rf, ok := ret.Get(0).(func(string) workqueue.RateLimitingInterface); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(workqueue.RateLimitingInterface)
		}
	}

	return r0
}

// MockQueuePair_SendQ_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendQ'
type MockQueuePair_SendQ_Call struct {
	*mock.Call
}

// SendQ is a helper method to define mock.On call
//   - name string
func (_e *MockQueuePair_Expecter) SendQ(name interface{}) *MockQueuePair_SendQ_Call {
	return &MockQueuePair_SendQ_Call{Call: _e.mock.On("SendQ", name)}
}

func (_c *MockQueuePair_SendQ_Call) Run(run func(name string)) *MockQueuePair_SendQ_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockQueuePair_SendQ_Call) Return(_a0 workqueue.RateLimitingInterface) *MockQueuePair_SendQ_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueuePair_SendQ_Call) RunAndReturn(run func(string) workqueue.RateLimitingInterface) *MockQueuePair_SendQ_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueuePair creates a new instance of MockQueuePair. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueuePair(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueuePair {
	mock := &MockQueuePair{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
