// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	workqueue "k8s.io/client-go/util/workqueue"
)

// QueuePair is an autogenerated mock type for the QueuePair type
type QueuePair struct {
	mock.Mock
}

// Create provides a mock function with given fields: name
func (_m *QueuePair) Create(name string) error {
	ret := _m.Called(name)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: name, shutdown
func (_m *QueuePair) Delete(name string, shutdown bool) error {
	ret := _m.Called(name, shutdown)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, bool) error); ok {
		r0 = rf(name, shutdown)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HasQueuePair provides a mock function with given fields: name
func (_m *QueuePair) HasQueuePair(name string) bool {
	ret := _m.Called(name)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Len provides a mock function with given fields:
func (_m *QueuePair) Len() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Names provides a mock function with given fields:
func (_m *QueuePair) Names() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// RecvQ provides a mock function with given fields: name
func (_m *QueuePair) RecvQ(name string) workqueue.RateLimitingInterface {
	ret := _m.Called(name)

	var r0 workqueue.RateLimitingInterface
	if rf, ok := ret.Get(0).(func(string) workqueue.RateLimitingInterface); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(workqueue.RateLimitingInterface)
		}
	}

	return r0
}

// SendQ provides a mock function with given fields: name
func (_m *QueuePair) SendQ(name string) workqueue.RateLimitingInterface {
	ret := _m.Called(name)

	var r0 workqueue.RateLimitingInterface
	if rf, ok := ret.Get(0).(func(string) workqueue.RateLimitingInterface); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(workqueue.RateLimitingInterface)
		}
	}

	return r0
}

// NewQueuePair creates a new instance of QueuePair. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueuePair(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueuePair {
	mock := &QueuePair{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
